CIRCUITPY_CREATOR_ID = 0xC3C30000
CIRCUITPY_CREATION_ID = 0x00C30003

USB_VID = 0x303A
USB_PID = 0x81B6
USB_PRODUCT = "T KEYBOARD"
USB_MANUFACTURER = "LILYGO"

IDF_TARGET = esp32c3

CIRCUITPY_ESP_FLASH_MODE = dio
CIRCUITPY_ESP_FLASH_FREQ = 80m
CIRCUITPY_ESP_FLASH_SIZE = 4MB

CIRCUITPY_ESP_USB_SERIAL_JTAG = 0

CIRCUITPY_BLEIO = 0
